os: Visual Studio 2015 CTP

init: 
build_script: 
  - cmd: appveyor-build.cmd

# scripts that run after cloning repository
install:
  # by default, all script lines are interpreted as batch
  - set PATH=%ProgramFiles(x86)%\MSBuild\14.0\Bin;%PATH%

test: off 
version: 0.0.1.{build} 
artifacts: 
  - path: Debug
    name: Debug
