os: Visual Studio 2015

environment:
  matrix:
    - BUILD_PROFILE: net40,portable7,portable47,portable78,portable259,vs
    - BUILD_PROFILE: cambridge_suite,qa_suite,smoke_only

init: 
build_script: 
  - cmd: appveyor-build.cmd %BUILD_PROFILE%

# scripts that run after cloning repository
install:
  # by default, all script lines are interpreted as batch
  - set PATH=%ProgramFiles(x86)%\MSBuild\14.0\Bin;%PATH%

test: off 
version: 0.0.1.{build} 
artifacts: 
  - path: Release
    name: Release